### PR TITLE
feat: imgix module compatible with 2.4.4 EE,ECE and CE and PHP8.1

### PR DESCRIPTION
**Pull request by mitesh-toptal**
The purpose of this PR is to imgix module compatible with Magento 2.4.4 EE, ECE and CE version, and PHP 8.1

### CODE REVIEW

**Review by sherwinski — COMMENTED** [review]
@mitesh-toptal Can you provide more details on these changes and why they correct the issues see from last time?
Also, there appears to be a lot of new code introduced in this PR. Can you please elaborate on why these changes are introduced and what purpose each one serves?

**Comment by mitesh-toptal** [comment]
**1. Block/Adminhtml/Product/Helper/Form/Gallery/Content.php**
**Comment:** Sometimes, When a product is save with image upload, without adding an imgix image on the admin side, it throws an error, So I just add the condition if the image is imgix image or not. 

**2. etc/adminhtml/di.xml**
**Comment:** When imgix image added into gallery and product save it throw an error for Magento ECE and EE version, because Magento_CatalogStaging module conflict with imgix module, So I updated this file.  

**3. view/adminhtml/templates/helper/gallery.phtml**
**Comment:** Actually this is the latest gallery from latest magento 2.4.4 which override in our custom module for add Add imgix image button in Image and Video section.

**4. view/adminhtml/web/js/imgix-modal.js
   view/adminhtml/web/js/new-imgix-dialog.js
   view/adminhtml/web/js/product-gallery.js**
**Comment:** In configurable product when imgix images are added from the admin side in the product gallery, images are added but when save and open product from the admin side, images are not appearing in the gallery, it is working with the simple product but not working with configurable product, so made changes of above js files.

**Comment by sherwinski** [comment]
>  In configurable product when imgix images are added from the admin side in the product gallery, images are added but when save and open product from the admin side, images are not appearing in the gallery, it is working with the simple product but not working with configurable product, so made changes of above js files.

@mitesh-toptal Could you provide a video of showing an example of this? I'm not sure I understand what "configurable product" vs "simple product" means in this scenario.

**Comment by mitesh-toptal** [comment]
Sure, This is the demo video for configurable and simple products, and replicating the issue, imgix image added in the simple and configurable product, but after save images are not displaying.
Demo video link: [https://drive.google.com/file/d/158XY7IAcrw9Y2JYPHQtzxbHy4XVqBabh/view](https://drive.google.com/file/d/158XY7IAcrw9Y2JYPHQtzxbHy4XVqBabh/view)

**Review by sherwinski — APPROVED** [review]
Thanks for providing more details. I have a much understanding of what's going on now.

**Pull request merged**
